from django.urls import path
from django.views.generic import RedirectView

from protocols import views, views_reports

app_name = "protocols"

urlpatterns = [
    # List and create
    path("", views.ProtocolListView.as_view(), name="protocol_list"),
    path(
        "select-type/",
        views.ProtocolSelectTypeView.as_view(),
        name="protocol_select_type",
    ),
    path(
        "create/cytology/",
        views.ProtocolCreateCytologyView.as_view(),
        name="protocol_create_cytology",
    ),
    path(
        "create/histopathology/",
        views.ProtocolCreateHistopathologyView.as_view(),
        name="protocol_create_histopathology",
    ),
    # Lab-delegated protocol creation (pilot)
    path(
        "lab/create/",
        views.LabProtocolVeterinarianSearchView.as_view(),
        name="lab_protocol_search",
    ),
    path(
        "lab/create/select-type/",
        views.LabProtocolSelectTypeView.as_view(),
        name="lab_protocol_select_type",
    ),
    path(
        "lab/create/cytology/",
        views.LabProtocolCreateCytologyView.as_view(),
        name="lab_protocol_create_cytology",
    ),
    path(
        "lab/create/histopathology/",
        views.LabProtocolCreateHistopathologyView.as_view(),
        name="lab_protocol_create_histopathology",
    ),
    # Detail, edit, delete
    path(
        "<int:pk>/", views.ProtocolDetailView.as_view(), name="protocol_detail"
    ),
    path(
        "<int:pk>/informe/imagenes/",
        views_reports.ProtocolReportImagesGalleryView.as_view(),
        name="protocol_report_images",
    ),
    path(
        "<int:pk>/informe/imagenes/<int:image_pk>/",
        views_reports.ProtocolReportImageDetailView.as_view(),
        name="protocol_report_image_detail",
    ),
    path(
        "public/<uuid:external_id>/",
        views.ProtocolPublicDetailView.as_view(),
        name="protocol_public_detail",
    ),
    path(
        "<int:pk>/edit/",
        views.ProtocolEditView.as_view(),
        name="protocol_edit",
    ),
    path(
        "<int:pk>/delete/",
        views.ProtocolDeleteView.as_view(),
        name="protocol_delete",
    ),
    path(
        "<int:pk>/submit/",
        views.ProtocolSubmitView.as_view(),
        name="protocol_submit",
    ),
    # Reception (laboratory staff only)
    path(
        "reception/",
        views.ReceptionPendingView.as_view(),
        name="reception",
    ),
    path(
        "reception/pending/",
        RedirectView.as_view(
            pattern_name="protocols:reception",
            permanent=True,
            query_string=True,
        ),
        name="reception_pending",
    ),
    path(
        "reception/<int:pk>/",
        RedirectView.as_view(
            pattern_name="protocols:reception_detail",
            permanent=False,
        ),
        name="reception_protocol",
    ),
    path(
        "reception/<int:pk>/confirm/",
        views.ReceptionConfirmView.as_view(),
        name="reception_confirm",
    ),
    path(
        "reception/<int:pk>/detail/",
        views.ReceptionDetailView.as_view(),
        name="reception_detail",
    ),
    path(
        "reception/<int:pk>/label/",
        views.ReceptionLabelPDFView.as_view(),
        name="reception_label",
    ),
    path(
        "reception/history/",
        views.ReceptionHistoryView.as_view(),
        name="reception_history",
    ),
    path(
        "rejected/",
        views.RejectedProtocolsView.as_view(),
        name="rejected_list",
    ),
    path(
        "<int:pk>/resubmit/",
        views.ProtocolResubmitView.as_view(),
        name="protocol_resubmit",
    ),
    # Processing (Step 05 - laboratory staff only)
    path(
        "processing/",
        views.ProcessingDashboardView.as_view(),
        name="processing_dashboard",
    ),
    path(
        "processing/queue/",
        views.ProcessingQueueView.as_view(),
        name="processing_queue",
    ),
    path(
        "processing/protocol/<int:pk>/",
        views.ProtocolProcessingStatusView.as_view(),
        name="processing_status",
    ),
    path(
        "processing/protocol/<int:pk>/mark-ready/",
        views.ProtocolMarkReadyView.as_view(),
        name="protocol_mark_ready",
    ),
    path(
        "processing/register/<int:protocol_pk>/",
        views.SampleRegistrationView.as_view(),
        name="sample_register",
    ),
    path(
        "processing/cassette/create/<int:protocol_pk>/",
        views.CassetteCreateView.as_view(),
        name="cassette_create",
    ),
    path(
        "processing/slide/register/<int:protocol_pk>/",
        views.SlideRegisterView.as_view(),
        name="slide_register",
    ),
    path(
        "processing/cassette/<int:cassette_pk>/stage/",
        views.CassetteUpdateStageView.as_view(),
        name="cassette_update_stage",
    ),
    path(
        "processing/cassette/<int:cassette_pk>/history/",
        views.CassetteProcessingHistoryView.as_view(),
        name="cassette_processing_history",
    ),
    path(
        "processing/slide/<int:slide_pk>/stage/",
        views.SlideUpdateStageView.as_view(),
        name="slide_update_stage",
    ),
    path(
        "processing/slide/<int:slide_pk>/history/",
        views.SlideProcessingHistoryView.as_view(),
        name="slide_processing_history",
    ),
    path(
        "processing/slide/<int:slide_pk>/quality/",
        views.SlideUpdateQualityView.as_view(),
        name="slide_update_quality",
    ),
    path(
        "processing/slide/<int:slide_pk>/delete/",
        views.SlideDeleteView.as_view(),
        name="slide_delete",
    ),
    # Reports
    path(
        "reports/pending/",
        views_reports.ReportPendingListView.as_view(),
        name="report_pending_list",
    ),
    path(
        "reports/history/",
        views_reports.ReportHistoryView.as_view(),
        name="report_history",
    ),
    path(
        "reports/mine/",
        views_reports.VeterinarianReportListView.as_view(),
        name="my_reports",
    ),
    path(
        "reports/create/<int:protocol_id>/",
        views_reports.ReportCreateView.as_view(),
        name="report_create",
    ),
    path(
        "reports/<int:pk>/edit/",
        views_reports.ReportEditView.as_view(),
        name="report_edit",
    ),
    path(
        "reports/<int:pk>/",
        views_reports.ReportDetailView.as_view(),
        name="report_detail",
    ),
    path(
        "reports/<int:pk>/finalize/",
        views_reports.ReportFinalizeView.as_view(),
        name="report_finalize",
    ),
    path(
        "reports/<int:pk>/pdf/",
        views_reports.ReportPDFView.as_view(),
        name="report_pdf",
    ),
    path(
        "reports/<int:pk>/send/",
        views_reports.ReportSendView.as_view(),
        name="report_send",
    ),
    # Work Orders (Step 07): UI/routes disabled — models kept for future use.
    # See roadmap item 6.1 and protocols.views_workorder.
]
