from django.urls import path

from protocols import views, views_reports, views_workorder

app_name = "protocols"

urlpatterns = [
    # List and create
    path("", views.ProtocolListView.as_view(), name="protocol_list"),
    path(
        "select-type/",
        views.ProtocolSelectTypeView.as_view(),
        name="protocol_select_type",
    ),
    path(
        "create/cytology/",
        views.ProtocolCreateCytologyView.as_view(),
        name="protocol_create_cytology",
    ),
    path(
        "create/histopathology/",
        views.ProtocolCreateHistopathologyView.as_view(),
        name="protocol_create_histopathology",
    ),
    # Detail, edit, delete
    path(
        "<int:pk>/", views.ProtocolDetailView.as_view(), name="protocol_detail"
    ),
    path(
        "public/<uuid:external_id>/",
        views.ProtocolPublicDetailView.as_view(),
        name="protocol_public_detail",
    ),
    path(
        "<int:pk>/edit/",
        views.ProtocolEditView.as_view(),
        name="protocol_edit",
    ),
    path(
        "<int:pk>/delete/",
        views.ProtocolDeleteView.as_view(),
        name="protocol_delete",
    ),
    path(
        "<int:pk>/submit/",
        views.ProtocolSubmitView.as_view(),
        name="protocol_submit",
    ),
    # Reception (laboratory staff only)
    path(
        "reception/",
        views.ReceptionSearchView.as_view(),
        name="reception_search",
    ),
    path(
        "reception/<int:pk>/confirm/",
        views.ReceptionConfirmView.as_view(),
        name="reception_confirm",
    ),
    path(
        "reception/<int:pk>/detail/",
        views.ReceptionDetailView.as_view(),
        name="reception_detail",
    ),
    path(
        "reception/<int:pk>/label/",
        views.ReceptionLabelPDFView.as_view(),
        name="reception_label",
    ),
    path(
        "reception/pending/",
        views.ReceptionPendingView.as_view(),
        name="reception_pending",
    ),
    path(
        "reception/history/",
        views.ReceptionHistoryView.as_view(),
        name="reception_history",
    ),
    path(
        "rejected/",
        views.RejectedProtocolsView.as_view(),
        name="rejected_list",
    ),
    # Processing (Step 05 - laboratory staff only)
    path(
        "processing/",
        views.ProcessingDashboardView.as_view(),
        name="processing_dashboard",
    ),
    path(
        "processing/queue/",
        views.ProcessingQueueView.as_view(),
        name="processing_queue",
    ),
    path(
        "processing/protocol/<int:pk>/",
        views.ProtocolProcessingStatusView.as_view(),
        name="processing_status",
    ),
    path(
        "processing/cassette/create/<int:protocol_pk>/",
        views.CassetteCreateView.as_view(),
        name="cassette_create",
    ),
    path(
        "processing/slide/register/<int:protocol_pk>/",
        views.SlideRegisterView.as_view(),
        name="slide_register",
    ),
    path(
        "processing/slide/<int:slide_pk>/stage/",
        views.SlideUpdateStageView.as_view(),
        name="slide_update_stage",
    ),
    path(
        "processing/slide/<int:slide_pk>/quality/",
        views.SlideUpdateQualityView.as_view(),
        name="slide_update_quality",
    ),
    # Reports
    path(
        "reports/pending/",
        views_reports.ReportPendingListView.as_view(),
        name="report_pending_list",
    ),
    path(
        "reports/history/",
        views_reports.ReportHistoryView.as_view(),
        name="report_history",
    ),
    path(
        "reports/create/<int:protocol_id>/",
        views_reports.ReportCreateView.as_view(),
        name="report_create",
    ),
    path(
        "reports/<int:pk>/edit/",
        views_reports.ReportEditView.as_view(),
        name="report_edit",
    ),
    path(
        "reports/<int:pk>/",
        views_reports.ReportDetailView.as_view(),
        name="report_detail",
    ),
    path(
        "reports/<int:pk>/finalize/",
        views_reports.ReportFinalizeView.as_view(),
        name="report_finalize",
    ),
    path(
        "reports/<int:pk>/pdf/",
        views_reports.ReportPDFView.as_view(),
        name="report_pdf",
    ),
    path(
        "reports/<int:pk>/send/",
        views_reports.ReportSendView.as_view(),
        name="report_send",
    ),
    # Work Orders (Step 07)
    path(
        "workorders/",
        views_workorder.WorkOrderListView.as_view(),
        name="workorder_list",
    ),
    path(
        "workorders/pending/",
        views_workorder.WorkOrderPendingProtocolsView.as_view(),
        name="workorder_pending_protocols",
    ),
    path(
        "workorders/select/<int:veterinarian_id>/",
        views_workorder.WorkOrderSelectProtocolsView.as_view(),
        name="workorder_select_protocols",
    ),
    path(
        "workorders/create/<str:protocol_ids>/",
        views_workorder.WorkOrderCreateView.as_view(),
        name="workorder_create_with_protocols",
    ),
    path(
        "workorders/<int:pk>/",
        views_workorder.WorkOrderDetailView.as_view(),
        name="workorder_detail",
    ),
    path(
        "workorders/<int:pk>/issue/",
        views_workorder.WorkOrderIssueView.as_view(),
        name="workorder_issue",
    ),
    path(
        "workorders/<int:pk>/send/",
        views_workorder.WorkOrderSendView.as_view(),
        name="workorder_send",
    ),
    path(
        "workorders/<int:pk>/pdf/",
        views_workorder.WorkOrderPDFView.as_view(),
        name="workorder_pdf",
    ),
]
