# Generated by Django 5.2.7 on 2025-10-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_veterinarian_address_veterinarianchangelog_and_more",
        ),
        ("protocols", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protocol",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "protocolo",
                "verbose_name_plural": "protocolos",
            },
        ),
        migrations.AlterField(
            model_name="protocol",
            name="academic_interest",
            field=models.BooleanField(
                default=False,
                help_text="Permitir uso con fines académicos/investigación",
                verbose_name="interés académico",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="age",
            field=models.CharField(
                blank=True,
                help_text='Ejemplo: "2 años", "6 meses"',
                max_length=50,
                verbose_name="edad",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("cytology", "Citología"),
                    ("histopathology", "Histopatología"),
                ],
                max_length=20,
                verbose_name="tipo de análisis",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="animal_identification",
            field=models.CharField(
                help_text="Nombre, número de caravana u otro identificador",
                max_length=200,
                verbose_name="identificación animal",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="breed",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="raza"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="clinical_history",
            field=models.TextField(
                blank=True, verbose_name="historia clínica"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="creado el"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="owner_first_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="nombre propietario"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="owner_last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="apellido propietario"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="presumptive_diagnosis",
            field=models.TextField(verbose_name="diagnóstico presuntivo"),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="protocol_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Número de protocolo final (ej: HP 24/001 o CT 24/001)",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="número de protocolo",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="reception_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha de recepción"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Macho"),
                    ("female", "Hembra"),
                    ("unknown", "Indeterminado"),
                ],
                max_length=20,
                verbose_name="sexo",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="species",
            field=models.CharField(max_length=100, verbose_name="especie"),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("submitted", "Enviado"),
                    ("received", "Recibido"),
                    ("processing", "En procesamiento"),
                    ("ready", "Listo"),
                    ("report_sent", "Informe enviado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="submission_date",
            field=models.DateField(verbose_name="fecha de remisión"),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="temporary_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código de seguimiento pre-recepción (ej: TMP-CT-20241010-456)",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="código temporal",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="actualizado el"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="veterinarian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="protocols",
                to="accounts.veterinarian",
                verbose_name="veterinario",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protocols",
                to="protocols.workorder",
                verbose_name="orden de trabajo",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("submitted", "Enviado"),
                    ("received", "Recibido"),
                    ("processing", "En procesamiento"),
                    ("ready", "Listo"),
                    ("report_sent", "Informe enviado"),
                ],
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
