# Generated by Django 5.2.7 on 2025-10-11 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_veterinarian_address_veterinarianchangelog_and_more",
        ),
        ("protocols", "0002_alter_protocol_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cytologysample",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "muestra de citología",
                "verbose_name_plural": "muestras de citología",
            },
        ),
        migrations.AlterModelOptions(
            name="histopathologysample",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "muestra de histopatología",
                "verbose_name_plural": "muestras de histopatología",
            },
        ),
        migrations.AlterModelOptions(
            name="protocolstatushistory",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "historial de estado del protocolo",
                "verbose_name_plural": "historiales de estado del protocolo",
            },
        ),
        migrations.AlterModelOptions(
            name="workorder",
            options={
                "verbose_name": "orden de trabajo",
                "verbose_name_plural": "órdenes de trabajo",
            },
        ),
        migrations.AlterField(
            model_name="cytologysample",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="creado el"
            ),
        ),
        migrations.AlterField(
            model_name="cytologysample",
            name="number_of_slides",
            field=models.IntegerField(
                default=1,
                help_text="Cantidad de portaobjetos enviados",
                verbose_name="número de portaobjetos",
            ),
        ),
        migrations.AlterField(
            model_name="cytologysample",
            name="observations",
            field=models.TextField(blank=True, verbose_name="observaciones"),
        ),
        migrations.AlterField(
            model_name="cytologysample",
            name="protocol",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cytology_sample",
                to="protocols.protocol",
                verbose_name="protocolo",
            ),
        ),
        migrations.AlterField(
            model_name="cytologysample",
            name="reception_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha de recepción"
            ),
        ),
        migrations.AlterField(
            model_name="cytologysample",
            name="sampling_site",
            field=models.CharField(
                help_text="Ubicación anatómica de la muestra",
                max_length=200,
                verbose_name="sitio de muestreo",
            ),
        ),
        migrations.AlterField(
            model_name="cytologysample",
            name="technique_used",
            field=models.CharField(
                help_text="Ej: Punción aspiración con aguja fina (PAAF), hisopado, raspado, etc.",
                max_length=200,
                verbose_name="técnica utilizada",
            ),
        ),
        migrations.AlterField(
            model_name="cytologysample",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="actualizado el"
            ),
        ),
        migrations.AlterField(
            model_name="cytologysample",
            name="veterinarian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cytology_samples",
                to="accounts.veterinarian",
                verbose_name="veterinario",
            ),
        ),
        migrations.AlterField(
            model_name="histopathologysample",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="creado el"
            ),
        ),
        migrations.AlterField(
            model_name="histopathologysample",
            name="material_submitted",
            field=models.TextField(
                help_text="Descripción de las muestras de tejido/órganos",
                verbose_name="material remitido",
            ),
        ),
        migrations.AlterField(
            model_name="histopathologysample",
            name="number_of_containers",
            field=models.IntegerField(
                default=1,
                help_text="Cantidad de frascos/contenedores enviados",
                verbose_name="número de frascos",
            ),
        ),
        migrations.AlterField(
            model_name="histopathologysample",
            name="observations",
            field=models.TextField(blank=True, verbose_name="observaciones"),
        ),
        migrations.AlterField(
            model_name="histopathologysample",
            name="preservation",
            field=models.CharField(
                default="Formol 10%",
                help_text="Método de conservación utilizado",
                max_length=100,
                verbose_name="conservación",
            ),
        ),
        migrations.AlterField(
            model_name="histopathologysample",
            name="protocol",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histopathology_sample",
                to="protocols.protocol",
                verbose_name="protocolo",
            ),
        ),
        migrations.AlterField(
            model_name="histopathologysample",
            name="reception_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha de recepción"
            ),
        ),
        migrations.AlterField(
            model_name="histopathologysample",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="actualizado el"
            ),
        ),
        migrations.AlterField(
            model_name="histopathologysample",
            name="veterinarian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="histopathology_samples",
                to="accounts.veterinarian",
                verbose_name="veterinario",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstatushistory",
            name="changed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="cambiado el"
            ),
        ),
        migrations.AlterField(
            model_name="protocolstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protocol_status_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="cambiado por",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstatushistory",
            name="description",
            field=models.TextField(blank=True, verbose_name="descripción"),
        ),
        migrations.AlterField(
            model_name="protocolstatushistory",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="protocols.protocol",
                verbose_name="protocolo",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("submitted", "Enviado"),
                    ("received", "Recibido"),
                    ("processing", "En procesamiento"),
                    ("ready", "Listo"),
                    ("report_sent", "Informe enviado"),
                ],
                max_length=20,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="creado el"
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="order_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="número de orden"
            ),
        ),
    ]
