# Generated by Django 5.2.7 on 2025-10-11 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0003_alter_cytologysample_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cytologysample",
            name="reception_date",
        ),
        migrations.RemoveField(
            model_name="histopathologysample",
            name="reception_date",
        ),
        migrations.AddField(
            model_name="cytologysample",
            name="number_slides_received",
            field=models.IntegerField(
                blank=True,
                help_text="Cantidad real de portaobjetos recibidos",
                null=True,
                verbose_name="número de portaobjetos recibidos",
            ),
        ),
        migrations.AddField(
            model_name="histopathologysample",
            name="number_jars_received",
            field=models.IntegerField(
                blank=True,
                help_text="Cantidad real de frascos recibidos",
                null=True,
                verbose_name="número de frascos recibidos",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="discrepancies",
            field=models.TextField(
                blank=True,
                help_text="Diferencias entre lo declarado y lo recibido",
                verbose_name="discrepancias",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que recepcionó la muestra",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_protocols",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recibido por",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="reception_notes",
            field=models.TextField(
                blank=True,
                help_text="Observaciones sobre la muestra al recibirla",
                verbose_name="observaciones de recepción",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="sample_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("optimal", "Óptima"),
                    ("acceptable", "Aceptable"),
                    ("suboptimal", "Subóptima"),
                    ("rejected", "Rechazada"),
                ],
                help_text="Estado de la muestra al momento de recepción",
                max_length=20,
                verbose_name="condición de la muestra",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="reception_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de recepción"
            ),
        ),
        migrations.CreateModel(
            name="ProtocolCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("cytology", "Citología"),
                            ("histopathology", "Histopatología"),
                        ],
                        max_length=20,
                        verbose_name="tipo de análisis",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Año para el contador", verbose_name="año"
                    ),
                ),
                (
                    "last_number",
                    models.IntegerField(
                        default=0,
                        help_text="Último número de protocolo asignado",
                        verbose_name="último número",
                    ),
                ),
            ],
            options={
                "verbose_name": "contador de protocolo",
                "verbose_name_plural": "contadores de protocolo",
                "indexes": [
                    models.Index(
                        fields=["analysis_type", "year"],
                        name="protocols_p_analysi_8675ee_idx",
                    )
                ],
                "unique_together": {("analysis_type", "year")},
            },
        ),
        migrations.CreateModel(
            name="ReceptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("received", "Recibido"),
                            ("rejected", "Rechazado"),
                            ("discrepancy_reported", "Discrepancia reportada"),
                            ("condition_noted", "Condición anotada"),
                        ],
                        max_length=100,
                        verbose_name="acción",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado el"
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_logs",
                        to="protocols.protocol",
                        verbose_name="protocolo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reception_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de recepción",
                "verbose_name_plural": "registros de recepción",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["protocol", "-created_at"],
                        name="protocols_r_protoco_7319d0_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="protocols_r_user_id_1f158a_idx",
                    ),
                ],
            },
        ),
    ]
