# Generated by Django 5.2.7 on 2025-10-11 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0004_remove_cytologysample_reception_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cassette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_cassette",
                    models.CharField(
                        db_index=True,
                        help_text="Ej: HP 24/123-C1",
                        max_length=50,
                        unique=True,
                        verbose_name="código de cassette",
                    ),
                ),
                (
                    "material_incluido",
                    models.TextField(
                        help_text="Descripción del tejido incluido en el cassette",
                        verbose_name="material incluido",
                    ),
                ),
                (
                    "tipo_cassette",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("multicorte", "Multicorte"),
                            ("coloracion_especial", "Coloración especial"),
                        ],
                        default="normal",
                        max_length=50,
                        verbose_name="tipo de cassette",
                    ),
                ),
                (
                    "color_cassette",
                    models.CharField(
                        choices=[
                            ("blanco", "Blanco"),
                            ("amarillo", "Amarillo"),
                            ("naranja", "Naranja"),
                        ],
                        default="blanco",
                        max_length=20,
                        verbose_name="color del cassette",
                    ),
                ),
                (
                    "fecha_encasetado",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que se colocó el tejido en el cassette",
                        null=True,
                        verbose_name="fecha de encasetado",
                    ),
                ),
                (
                    "fecha_fijacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de inicio de fijación",
                        null=True,
                        verbose_name="fecha de fijación",
                    ),
                ),
                (
                    "fecha_inclusion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de inclusión en parafina",
                        null=True,
                        verbose_name="fecha de inclusión",
                    ),
                ),
                (
                    "fecha_entacado",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de creación del taco de parafina",
                        null=True,
                        verbose_name="fecha de entacado",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En proceso"),
                            ("completado", "Completado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="actualizado el"
                    ),
                ),
                (
                    "histopathology_sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cassettes",
                        to="protocols.histopathologysample",
                        verbose_name="muestra de histopatología",
                    ),
                ),
            ],
            options={
                "verbose_name": "cassette",
                "verbose_name_plural": "cassettes",
                "ordering": ["codigo_cassette"],
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_portaobjetos",
                    models.CharField(
                        db_index=True,
                        help_text="Ej: HP 24/123-S1 o CT 24/089-S1",
                        max_length=50,
                        unique=True,
                        verbose_name="código de portaobjetos",
                    ),
                ),
                (
                    "campo",
                    models.IntegerField(
                        blank=True,
                        help_text="Número de campo del portaobjetos",
                        null=True,
                        verbose_name="campo",
                    ),
                ),
                (
                    "tecnica_coloracion",
                    models.CharField(
                        default="Hematoxilina-Eosina",
                        help_text="Técnica de coloración utilizada",
                        max_length=200,
                        verbose_name="técnica de coloración",
                    ),
                ),
                (
                    "fecha_montaje",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de montaje"
                    ),
                ),
                (
                    "fecha_coloracion",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="fecha de coloración",
                    ),
                ),
                (
                    "calidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excelente", "Excelente"),
                            ("buena", "Buena"),
                            ("aceptable", "Aceptable"),
                            ("deficiente", "Deficiente"),
                        ],
                        help_text="Calidad del portaobjetos",
                        max_length=20,
                        verbose_name="calidad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("montado", "Montado"),
                            ("coloreado", "Coloreado"),
                            ("listo", "Listo"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="actualizado el"
                    ),
                ),
                (
                    "cytology_sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="protocols.cytologysample",
                        verbose_name="muestra de citología",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="protocols.protocol",
                        verbose_name="protocolo",
                    ),
                ),
            ],
            options={
                "verbose_name": "portaobjetos",
                "verbose_name_plural": "portaobjetos",
                "ordering": ["codigo_portaobjetos"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("encasetado", "Encasetado"),
                            ("fijacion", "Fijación"),
                            ("inclusion", "Inclusión"),
                            ("entacado", "Entacado"),
                            ("corte", "Corte"),
                            ("montaje", "Montaje"),
                            ("coloracion", "Coloración"),
                        ],
                        max_length=50,
                        verbose_name="etapa",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de fin"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado el"
                    ),
                ),
                (
                    "cassette",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="protocols.cassette",
                        verbose_name="cassette",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="protocols.protocol",
                        verbose_name="protocolo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="protocols.slide",
                        verbose_name="portaobjetos",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de procesamiento",
                "verbose_name_plural": "registros de procesamiento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CassetteSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posicion",
                    models.CharField(
                        choices=[
                            ("superior", "Superior"),
                            ("inferior", "Inferior"),
                            ("completo", "Completo"),
                        ],
                        default="completo",
                        help_text="Posición del cassette en el portaobjetos",
                        max_length=20,
                        verbose_name="posición",
                    ),
                ),
                (
                    "coloracion",
                    models.CharField(
                        blank=True,
                        help_text="Coloración específica para este cassette en este portaobjetos",
                        max_length=200,
                        verbose_name="coloración",
                    ),
                ),
                (
                    "requiere_multicorte",
                    models.BooleanField(
                        default=False, verbose_name="requiere multicorte"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado el"
                    ),
                ),
                (
                    "cassette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cassette_slides",
                        to="protocols.cassette",
                        verbose_name="cassette",
                    ),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cassette_slides",
                        to="protocols.slide",
                        verbose_name="portaobjetos",
                    ),
                ),
            ],
            options={
                "verbose_name": "cassette-portaobjetos",
                "verbose_name_plural": "cassette-portaobjetos",
            },
        ),
        migrations.AddIndex(
            model_name="cassette",
            index=models.Index(
                fields=["codigo_cassette"],
                name="protocols_c_codigo__c88830_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cassette",
            index=models.Index(
                fields=["histopathology_sample", "created_at"],
                name="protocols_c_histopa_87b908_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cassette",
            index=models.Index(
                fields=["estado"], name="protocols_c_estado_27fe7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slide",
            index=models.Index(
                fields=["codigo_portaobjetos"],
                name="protocols_s_codigo__65b5d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="slide",
            index=models.Index(
                fields=["protocol", "created_at"],
                name="protocols_s_protoco_5b6224_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="slide",
            index=models.Index(
                fields=["estado"], name="protocols_s_estado_790293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["protocol", "-created_at"],
                name="protocols_p_protoco_579e8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["cassette", "-created_at"],
                name="protocols_p_cassett_53f481_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["slide", "-created_at"],
                name="protocols_p_slide_i_475db9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["usuario", "-created_at"],
                name="protocols_p_usuario_0b69c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cassetteslide",
            index=models.Index(
                fields=["cassette"], name="protocols_c_cassett_019d94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cassetteslide",
            index=models.Index(
                fields=["slide"], name="protocols_c_slide_i_09600c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cassetteslide",
            unique_together={("cassette", "slide")},
        ),
    ]
