# Generated by Django 5.2.7 on 2025-10-12 04:32

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_histopathologist"),
        ("protocols", "0006_protocol_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "macroscopic_observations",
                    models.TextField(
                        blank=True,
                        help_text="Descripción macroscópica del material recibido",
                        verbose_name="observaciones macroscópicas",
                    ),
                ),
                (
                    "microscopic_observations",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones microscópicas generales",
                        verbose_name="observaciones microscópicas",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        help_text="Diagnóstico patológico final",
                        verbose_name="diagnóstico",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios adicionales sobre el caso",
                        verbose_name="comentarios",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recomendaciones clínicas para el veterinario",
                        verbose_name="recomendaciones",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Fecha de emisión del informe",
                        verbose_name="fecha del informe",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Número de versión del informe",
                        verbose_name="versión",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("finalized", "Finalizado"),
                            ("sent", "Enviado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "pdf_path",
                    models.CharField(
                        blank=True,
                        help_text="Ruta del archivo PDF generado",
                        max_length=500,
                        verbose_name="ruta del PDF",
                    ),
                ),
                (
                    "pdf_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash para verificar integridad",
                        max_length=64,
                        verbose_name="hash del PDF",
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de envío"
                    ),
                ),
                (
                    "sent_to_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email al que se envió el informe",
                        max_length=254,
                        verbose_name="enviado a",
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                            ("bounced", "Rebotado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado del email",
                    ),
                ),
                (
                    "email_error",
                    models.TextField(
                        blank=True,
                        help_text="Detalles del error si el envío falló",
                        verbose_name="error de email",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="actualizado el"
                    ),
                ),
                (
                    "histopathologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="accounts.histopathologist",
                        verbose_name="histopatólogo",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="protocols.protocol",
                        verbose_name="protocolo",
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_reports",
                        to="accounts.veterinarian",
                        verbose_name="veterinario",
                    ),
                ),
            ],
            options={
                "verbose_name": "informe",
                "verbose_name_plural": "informes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CassetteObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        help_text="Observaciones microscópicas del cassette",
                        verbose_name="observaciones",
                    ),
                ),
                (
                    "partial_diagnosis",
                    models.TextField(
                        blank=True,
                        help_text="Diagnóstico específico para este cassette",
                        verbose_name="diagnóstico parcial",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de presentación en el informe",
                        verbose_name="orden",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="actualizado el"
                    ),
                ),
                (
                    "cassette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="protocols.cassette",
                        verbose_name="cassette",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cassette_observations",
                        to="protocols.report",
                        verbose_name="informe",
                    ),
                ),
            ],
            options={
                "verbose_name": "observación de cassette",
                "verbose_name_plural": "observaciones de cassettes",
                "ordering": ["order", "cassette__codigo_cassette"],
            },
        ),
        migrations.CreateModel(
            name="ReportImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="Ruta del archivo de imagen",
                        max_length=500,
                        verbose_name="ruta de imagen",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de lo que muestra la imagen",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "magnification",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 400x, 100x",
                        max_length=50,
                        verbose_name="magnificación",
                    ),
                ),
                (
                    "technique",
                    models.CharField(
                        blank=True,
                        help_text="Ej: H&E, PAS, Tricrómico de Masson",
                        max_length=100,
                        verbose_name="técnica",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de presentación en el informe",
                        verbose_name="orden",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado el"
                    ),
                ),
                (
                    "cassette",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_images",
                        to="protocols.cassette",
                        verbose_name="cassette",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="protocols.report",
                        verbose_name="informe",
                    ),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_images",
                        to="protocols.slide",
                        verbose_name="portaobjetos",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen de informe",
                "verbose_name_plural": "imágenes de informe",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["protocol"], name="protocols_r_protoco_c6b380_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["histopathologist", "-created_at"],
                name="protocols_r_histopa_cb8db9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["veterinarian", "-created_at"],
                name="protocols_r_veterin_67c561_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "-created_at"],
                name="protocols_r_status_3f23fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["-report_date"], name="protocols_r_report__ab7f92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cassetteobservation",
            index=models.Index(
                fields=["report", "order"],
                name="protocols_c_report__8bb2aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cassetteobservation",
            index=models.Index(
                fields=["cassette"], name="protocols_c_cassett_2e8ae1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cassetteobservation",
            unique_together={("report", "cassette")},
        ),
        migrations.AddIndex(
            model_name="reportimage",
            index=models.Index(
                fields=["report", "order"],
                name="protocols_r_report__82037f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportimage",
            index=models.Index(
                fields=["cassette"], name="protocols_r_cassett_67b633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportimage",
            index=models.Index(
                fields=["slide"], name="protocols_r_slide_i_bb64b0_idx"
            ),
        ),
    ]
