# Generated by Django 5.2.7 on 2025-10-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0009_add_email_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryCodeCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("cytology", "Citología"),
                            ("histopathology", "Histopatología"),
                        ],
                        max_length=20,
                        verbose_name="tipo de análisis",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Fecha para el contador",
                        verbose_name="fecha",
                    ),
                ),
                (
                    "last_number",
                    models.IntegerField(
                        default=0,
                        help_text="Último número de código temporal asignado",
                        verbose_name="último número",
                    ),
                ),
            ],
            options={
                "verbose_name": "contador de código temporal",
                "verbose_name_plural": "contadores de código temporal",
                "indexes": [
                    models.Index(
                        fields=["analysis_type", "date"],
                        name="protocols_t_analysi_a3b2e1_idx",
                    )
                ],
                "unique_together": {("analysis_type", "date")},
            },
        ),
    ]
