# Generated by Django 5.2.7 on 2026-02-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_laboratorystaff"),
        ("protocols", "0012_alter_protocol_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="laboratory_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="accounts.laboratorystaff",
                verbose_name="personal de laboratorio",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["laboratory_staff", "-created_at"],
                name="protocols_r_laborat_aae9e8_idx",
            ),
        ),
    ]
