# Generated by Django 5.2.7 on 2026-02-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_laboratorystaff"),
        ("protocols", "0013_report_laboratory_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="histopathologist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="accounts.histopathologist",
                verbose_name="histopatólogo",
            ),
        ),
    ]
