# Generated by Django 5.2.11 on 2026-03-15 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0014_report_histopathologist_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("submitted", "Protocolo enviado"),
                            ("reception", "Muestra recibida"),
                            ("rejection", "Muestra rechazada"),
                            ("discrepancy", "Discrepancias en recepción"),
                            ("ready", "Muestra lista para diagnóstico"),
                            ("report_ready", "Informe disponible"),
                            ("work_order", "Orden de trabajo"),
                            ("custom", "Notificación personalizada"),
                        ],
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="título"),
                ),
                ("body", models.TextField(blank=True, verbose_name="cuerpo")),
                (
                    "link_url",
                    models.URLField(blank=True, verbose_name="enlace"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="leída"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="leída el"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creada el"
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="in_app_notifications",
                        to="protocols.protocol",
                        verbose_name="protocolo",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_app_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinatario",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="in_app_notifications",
                        to="protocols.workorder",
                        verbose_name="orden de trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación in-app",
                "verbose_name_plural": "notificaciones in-app",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="inapp_notif_recip_read_created",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="inapp_notif_recip_created",
                    ),
                ],
            },
        ),
    ]
