# Generated by Django 5.2.11 on 2026-05-19 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0015_add_inapp_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cassette",
            name="color_cassette",
        ),
        migrations.RemoveField(
            model_name="cassette",
            name="tipo_cassette",
        ),
    ]
