# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0016_remove_cassette_tipo_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inappnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("submitted", "Protocolo enviado"),
                    ("reception", "Muestra recibida"),
                    ("rejection", "Muestra rechazada"),
                    ("discrepancy", "Discrepancias en recepción"),
                    ("ready", "Muestra lista para diagnóstico"),
                    ("report_ready", "Informe disponible"),
                    ("work_order", "Orden de trabajo"),
                    ("custom", "Notificación personalizada"),
                    ("announcement", "Aviso general"),
                ],
                max_length=30,
                verbose_name="tipo",
            ),
        ),
    ]
