# Generated by Django 5.2.11 on 2026-06-28 23:53

from urllib.parse import urlparse

from django.db import migrations, models


def normalize_notification_link_urls(apps, schema_editor):
    """Convert legacy absolute notification URLs to root-relative paths."""
    InAppNotification = apps.get_model("protocols", "InAppNotification")
    for notification in InAppNotification.objects.exclude(link_url=""):
        link_url = notification.link_url
        if link_url.startswith("/") and not link_url.startswith("//"):
            continue
        parsed = urlparse(link_url)
        if not parsed.scheme or not parsed.netloc:
            continue
        path = parsed.path or "/"
        if parsed.query:
            path = f"{path}?{parsed.query}"
        notification.link_url = path
        notification.save(update_fields=["link_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0018_reportimage_file_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inappnotification",
            name="link_url",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Ruta relativa o URL de destino al abrir la notificación"
                ),
                max_length=500,
                verbose_name="enlace",
            ),
        ),
        migrations.RunPython(
            normalize_notification_link_urls,
            migrations.RunPython.noop,
        ),
    ]
