# Generated by Django 5.2.11 on 2026-07-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0020_normalize_cytology_technique_paaf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cytologysample",
            name="technique_used",
            field=models.CharField(
                help_text="Ej: Punción (PAAF), hisopado, raspado, etc.",
                max_length=200,
                verbose_name="técnica utilizada",
            ),
        ),
    ]
