# Generated by Django 5.2.11 on 2026-07-09 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0021_alter_cytologysample_technique_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que cargó el protocolo (p. ej. personal de laboratorio)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protocols_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creado por",
            ),
        ),
    ]
