# Generated by Django 5.2.11 on 2026-07-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0022_protocol_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="animal_category",
            field=models.CharField(
                blank=True,
                help_text="Clasificación o categoría del animal (ej. mascota, ganado)",
                max_length=100,
                verbose_name="categoría del animal",
            ),
        ),
        migrations.AddField(
            model_name="reportimage",
            name="include_in_pdf",
            field=models.BooleanField(
                default=True,
                help_text="Si está desmarcado, la imagen se conserva en el informe digital pero no se imprime en el PDF enviado.",
                verbose_name="incluir en PDF",
            ),
        ),
    ]
