# Generated by Django 5.2.14 on 2026-07-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0023_animal_category_and_pdf_image_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("email_verification", "Verificación de Email"),
                    ("password_reset", "Restablecimiento de Contraseña"),
                    ("sample_reception", "Recepción de Muestra"),
                    ("report_ready", "Informe Listo"),
                    ("work_order", "Orden de Trabajo"),
                    ("custom", "Notificación Personalizada"),
                    ("veterinarian_approved", "Veterinario Habilitado"),
                    (
                        "veterinarian_account_removed",
                        "Cuenta de Veterinario Eliminada",
                    ),
                ],
                max_length=50,
                verbose_name="tipo de email",
            ),
        ),
    ]
