# Generated by Django 5.2 on 2025-06-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_veterinarian_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this veterinarian has been approved by an admin.'),
        ),
    ]
