# Generated by Django 5.2.11 on 2026-03-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServerStatsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="JSON: system, docker, storage keys as returned by server_stats_service",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Actualizado"
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de estadísticas del servidor",
                "verbose_name_plural": "Snapshots de estadísticas del servidor",
            },
        ),
    ]
