"""
Django settings for adlab project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import socket
import sys
from pathlib import Path

import sentry_sdk
from distutils.util import strtobool
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import ignore_logger

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(strtobool(os.getenv("DEBUG", "false")))

# Detect if we're running tests
TESTING = (
    "test" in sys.argv
    or "pytest" in sys.argv[0]
    or os.getenv("DJANGO_TESTING", "").lower() == "true"
    or os.getenv("RUNNING_TESTS", "").lower() == "true"
)

# Test configuration
if TESTING:
    # Use custom test runner that handles database cleanup properly
    TEST_RUNNER = "config.test_runner.DockerTestRunner"
    print(f"Using custom test runner: {TEST_RUNNER}")
    print("TESTING mode enabled - Celery will run synchronously")

    # Ensure tests run sequentially to avoid deadlocks
    os.environ.setdefault("DJANGO_TEST_PROCESSES", "1")

# https://docs.djangoproject.com/en/5.2/ref/settings/#std:setting-ALLOWED_HOSTS
allowed_hosts = os.getenv("ALLOWED_HOSTS", ".localhost,127.0.0.1,[::1]")
ALLOWED_HOSTS = list(map(str.strip, allowed_hosts.split(",")))

# Sentry Configuration
sentry_dsn = os.getenv("SENTRY_DSN")
if sentry_dsn:
    sentry_environment = os.getenv("SENTRY_ENVIRONMENT", "development")
    sentry_traces_sample_rate = float(
        os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1" if DEBUG else "1.0")
    )
    sentry_profiles_sample_rate = float(
        os.getenv("SENTRY_PROFILES_SAMPLE_RATE", "0.0" if DEBUG else "1.0")
    )

    sentry_sdk.init(
        dsn=sentry_dsn,
        integrations=[DjangoIntegration()],
        environment=sentry_environment,
        send_default_pii=True,
        traces_sample_rate=sentry_traces_sample_rate,
        profile_session_sample_rate=sentry_profiles_sample_rate,
        profile_lifecycle="trace" if not DEBUG else "off",
        enable_logs=True,
    )

    ignore_logger("gunicorn.access")

# Application definitions
INSTALLED_APPS = [
    "accounts.apps.AccountsConfig",
    "pages.apps.PagesConfig",
    "protocols.apps.ProtocolsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "config.middleware.DocsIndexMiddleware",  # Serve index.html for MkDocs URLs
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.VeterinarianProfileRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if not TESTING and DEBUG:
    INSTALLED_APPS = [*INSTALLED_APPS, "debug_toolbar"]
    MIDDLEWARE = [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        *MIDDLEWARE,
    ]

ROOT_URLCONF = "config.urls"

# Starting with Django 4.1+ we need to pick which template loaders to use
# based on our environment since 4.1+ will cache templates by default.
default_loaders = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

cached_loaders = [("django.template.loaders.cached.Loader", default_loaders)]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": default_loaders if DEBUG else cached_loaders,
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Authentication
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-user-model
AUTH_USER_MODEL = "accounts.User"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "adlab"),
        "USER": os.getenv("POSTGRES_USER", "adlab"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "password"),
        "HOST": os.getenv("POSTGRES_HOST", "postgres"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "TEST": {
            "NAME": f"test_{os.getenv('POSTGRES_DB', 'adlab')}",
            "CONN_MAX_AGE": 0,  # Don't persist connections during tests
        },
        "CONN_MAX_AGE": 0
        if TESTING
        else 60,  # No persistent connections during tests
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa: E501
    },
]

# Sessions
# https://docs.djangoproject.com/en/5.2/ref/settings/#sessions
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

# Redis
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")

# Caching
# https://docs.djangoproject.com/en/5.2/topics/cache/
if TESTING:
    # Use in-memory cache for tests (faster and doesn't require Redis)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
    print("TESTING mode: Using LocMemCache for tests")
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }

# Celery
# https://docs.celeryproject.org/en/stable/userguide/configuration.html
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Argentina/Buenos_Aires"

# Task configuration
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes

# Retry configuration
CELERY_TASK_ACKS_LATE = True  # Tasks acknowledged after completion
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Test-specific Celery configuration
if TESTING:
    # Run tasks synchronously during tests (no worker needed)
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    # Use in-memory broker for tests
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"

# Celery Beat: periodic tasks (only applied when beat is running)
# https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html
CELERY_BEAT_SCHEDULE = {
    "check-container-memory-alerts": {
        "task": "protocols.tasks.check_container_memory_alerts",
        "schedule": 600.0,  # Every 10 minutes
        "options": {"queue": "default"},
    },
}

# Container memory alert: threshold (percent) and optional name substring filter.
# Containers with memory_percent >= threshold are reported to admins (email).
# Set to 0 to disable alerting.
CONTAINER_MEMORY_ALERT_THRESHOLD = int(
    os.getenv("CONTAINER_MEMORY_ALERT_THRESHOLD", "85")
)
# Only check containers whose name contains this string (e.g. "laboratory-web").
# Empty string = check all containers.
CONTAINER_MEMORY_ALERT_NAME_FILTER = os.getenv(
    "CONTAINER_MEMORY_ALERT_NAME_FILTER", "laboratory-web"
)
# After sending an alert, do not send again for this many seconds (cooldown).
CONTAINER_MEMORY_ALERT_COOLDOWN_SECONDS = int(
    os.getenv("CONTAINER_MEMORY_ALERT_COOLDOWN_SECONDS", "3600")
)  # 1 hour

# Authentication settings
# Session configuration
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 7200  # 2 hours in seconds
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_SAVE_EVERY_REQUEST = True  # Extend session on each request

# Login/logout URLs
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Password validation
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour in seconds

# Site URL for building absolute URLs in emails
SITE_URL = os.getenv(
    "SITE_URL", "http://localhost:8000" if DEBUG else "https://adlab.com"
)

# Email configuration
# For development, use console backend. In production, configure SMTP.
# Optional: set TESTING_EMAIL=true to send real emails via Gmail (Google account + app password).
# Never use TESTING_EMAIL when running tests (CI or local); see override below.
TESTING_EMAIL = bool(strtobool(os.getenv("TESTING_EMAIL", "false")))
if TESTING:
    TESTING_EMAIL = False  # Never send real email from test runs (CI or local)

if TESTING_EMAIL:
    # Use Gmail SMTP with a Google account and app password.
    # Set TESTING_EMAIL_USER (your Gmail) and TESTING_EMAIL_APP_PASSWORD (16-char app password).
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("TESTING_EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("TESTING_EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.getenv("TESTING_EMAIL_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("TESTING_EMAIL_APP_PASSWORD", "")
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    DEFAULT_FROM_EMAIL = os.getenv(
        "TESTING_EMAIL_FROM",
        os.getenv("TESTING_EMAIL_USER", "noreply@adlab.com"),
    )
    SERVER_EMAIL = os.getenv(
        "TESTING_EMAIL_SERVER",
        os.getenv("TESTING_EMAIL_USER", "server@adlab.com"),
    )
else:
    EMAIL_BACKEND = os.getenv(
        "EMAIL_BACKEND",
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend",
    )
    EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = bool(strtobool(os.getenv("EMAIL_USE_TLS", "true")))
    EMAIL_USE_SSL = bool(strtobool(os.getenv("EMAIL_USE_SSL", "false")))
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@adlab.com")
    SERVER_EMAIL = os.getenv("SERVER_EMAIL", "server@adlab.com")

# Security settings for production
# https://docs.djangoproject.com/en/5.2/ref/settings/#security
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = bool(
        strtobool(os.getenv("SECURE_SSL_REDIRECT", "true"))
    )
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # CSRF settings
    csrf_trusted_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
    if csrf_trusted_origins:
        CSRF_TRUSTED_ORIGINS = list(
            map(str.strip, csrf_trusted_origins.split(","))
        )

    # Content Security Policy
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = ["/public", os.path.join(BASE_DIR, "..", "public")]
STATIC_ROOT = "/public_collected"

# Media files (user uploads: signatures, reports, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "..", "media")

# Object storage (Garage / S3)
USE_S3_STORAGE = bool(strtobool(os.getenv("USE_S3_STORAGE", "false")))

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "config.storage.ForgivingManifestStaticFilesStorage",
        "OPTIONS": {
            "location": "/public_collected",
            "base_url": "/static/",
        },
    },
}

if USE_S3_STORAGE and not TESTING:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
            "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),
            "bucket_name": os.getenv("AWS_STORAGE_BUCKET_NAME", "adlab-media"),
            "endpoint_url": os.getenv("AWS_S3_ENDPOINT_URL"),
            "region_name": os.getenv("AWS_S3_REGION_NAME", "garage"),
            "addressing_style": os.getenv("AWS_S3_ADDRESSING_STYLE", "path"),
            "signature_version": "s3v4",
            "default_acl": None,
            "querystring_auth": False,
            "file_overwrite": False,
            "use_ssl": False,
        },
    }

# Test-specific static files configuration
if TESTING:
    MEDIA_ROOT = os.path.join(BASE_DIR, "..", "tmp_test_media")
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Django Debug Toolbar
# https://django-debug-toolbar.readthedocs.io/
if DEBUG:
    # We need to configure an IP address to allow connections from, but in
    # Docker we can't use 127.0.0.1 since this runs in a container but we want
    # to access the toolbar from our browser outside of the container.
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + [
        "127.0.0.1",
        "10.0.2.2",
    ]
