# Generated by Django 5.2.7 on 2025-10-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="email verification sent at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="email verification token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False, verbose_name="email verified"
            ),
        ),
        migrations.AlterField(
            model_name="authauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                    ("password_reset_request", "Password Reset Request"),
                    ("password_reset_complete", "Password Reset Complete"),
                    ("account_locked", "Account Locked"),
                    ("account_unlocked", "Account Unlocked"),
                    ("password_changed", "Password Changed"),
                    ("email_verification_sent", "Email Verification Sent"),
                    ("email_verified", "Email Verified"),
                    ("email_verification_failed", "Email Verification Failed"),
                ],
                max_length=50,
                verbose_name="action",
            ),
        ),
    ]
