# Generated by Django 5.2.7 on 2025-10-11 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Veterinarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=100, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Professional license number (matrícula). Example: MP-12345",
                        max_length=50,
                        unique=True,
                        verbose_name="license number",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Argentine format: +54 XXX XXXXXXX",
                        max_length=50,
                        verbose_name="phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Denormalized for quick access",
                        max_length=255,
                        verbose_name="email",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="is verified"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verified at"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin notes about verification process",
                        verbose_name="verification notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinarian_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_veterinarians",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="verified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "veterinarian",
                "verbose_name_plural": "veterinarians",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province",
                    models.CharField(max_length=100, verbose_name="province"),
                ),
                (
                    "locality",
                    models.CharField(max_length=100, verbose_name="locality"),
                ),
                (
                    "street",
                    models.CharField(max_length=200, verbose_name="street"),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="number"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="floor"
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="apartment"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional address information",
                        verbose_name="notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "veterinarian",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="accounts.veterinarian",
                        verbose_name="veterinarian",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.CreateModel(
            name="VeterinarianChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=50, verbose_name="field name"),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, verbose_name="old value"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, verbose_name="new value"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="changed at"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veterinarian_changes_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="changed by",
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="accounts.veterinarian",
                        verbose_name="veterinarian",
                    ),
                ),
            ],
            options={
                "verbose_name": "veterinarian change log",
                "verbose_name_plural": "veterinarian change logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="veterinarian",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="accounts_ve_last_na_efa197_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="veterinarian",
            index=models.Index(
                fields=["license_number"],
                name="accounts_ve_license_131272_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="veterinarian",
            index=models.Index(
                fields=["email"], name="accounts_ve_email_b20ed3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="veterinarian",
            index=models.Index(
                fields=["is_verified"], name="accounts_ve_is_veri_748d9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["province"], name="accounts_ad_provinc_9371c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["locality"], name="accounts_ad_localit_7b6e82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="veterinarianchangelog",
            index=models.Index(
                fields=["veterinarian", "-changed_at"],
                name="accounts_ve_veterin_1d23c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="veterinarianchangelog",
            index=models.Index(
                fields=["-changed_at"], name="accounts_ve_changed_3a7de8_idx"
            ),
        ),
    ]
