# Generated by Django 5.2.7 on 2025-10-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_authauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='cuil_cuit',
            field=models.CharField(default='', help_text='Código Único de Identificación Laboral. Formato: XX-XXXXXXXX-X', max_length=20, verbose_name='CUIL/CUIT'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad (7-8 dígitos)', max_length=20, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='license_number',
            field=models.CharField(blank=True, help_text='Professional license number (matrícula). Example: MP-12345 (optional)', max_length=50, null=True, unique=True, verbose_name='license number'),
        ),
        migrations.AddIndex(
            model_name='veterinarian',
            index=models.Index(fields=['cuil_cuit'], name='accounts_ve_cuil_cu_33ebfb_idx'),
        ),
    ]
