# Generated by Django 5.2.7 on 2026-02-14 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_update_veterinarian_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaboratoryStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Apellido del personal de laboratorio",
                        max_length=100,
                        verbose_name="apellido",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del personal de laboratorio",
                        max_length=100,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Número de matrícula profesional",
                        max_length=50,
                        unique=True,
                        verbose_name="número de matrícula",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Profesor Titular, Profesor Asociado, Jefe de TP",
                        max_length=100,
                        verbose_name="cargo",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="Especialidad o área de expertise",
                        max_length=200,
                        verbose_name="especialidad",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de la firma para incluir en informes",
                        null=True,
                        upload_to="signatures/lab_staff/",
                        verbose_name="firma digital",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono de contacto",
                        max_length=20,
                        verbose_name="teléfono",
                    ),
                ),
                (
                    "can_create_reports",
                    models.BooleanField(
                        default=True,
                        help_text="Si el personal puede crear y firmar informes patológicos",
                        verbose_name="puede crear informes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si el personal está activo para trabajar en el laboratorio",
                        verbose_name="activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="actualizado el"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratory_staff_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "personal de laboratorio",
                "verbose_name_plural": "personal de laboratorio",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["license_number"],
                        name="accounts_la_license_591993_idx",
                    ),
                    models.Index(
                        fields=["is_active"],
                        name="accounts_la_is_acti_2cc234_idx",
                    ),
                    models.Index(
                        fields=["can_create_reports"],
                        name="accounts_la_can_cre_dc2d8b_idx",
                    ),
                ],
            },
        ),
    ]
