# Generated by Django 5.2.14 on 2026-07-09 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_migrate_histopathologists_to_laboratory_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                    ("password_reset_request", "Password Reset Request"),
                    ("password_reset_complete", "Password Reset Complete"),
                    ("account_locked", "Account Locked"),
                    ("account_unlocked", "Account Unlocked"),
                    ("password_changed", "Password Changed"),
                    ("email_verification_sent", "Email Verification Sent"),
                    ("email_verified", "Email Verified"),
                    ("email_verification_failed", "Email Verification Failed"),
                    ("user_created", "Usuario Creado"),
                    ("veterinarian_approved", "Veterinario Habilitado"),
                    ("veterinarian_deleted", "Veterinario Eliminado"),
                    ("veterinarian_reactivated", "Veterinario Reactivado"),
                ],
                max_length=50,
                verbose_name="action",
            ),
        ),
        migrations.CreateModel(
            name="VeterinarianPendingApprovalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Cuenta pendiente de habilitación",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Texto en Markdown (negrita, enlaces, listas).",
                        verbose_name="Mensaje",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Teléfono de contacto",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Email de contacto",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si está desactivado, se muestra un mensaje genérico.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Actualizado el"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vet_pending_settings_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pantalla pendiente de habilitación",
                "verbose_name_plural": "Pantallas pendiente de habilitación",
            },
        ),
    ]
