# Generated by Django 5.2.14 on 2026-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_normalize_empty_license_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="histopathologist",
            name="signature_affiliation_text",
            field=models.TextField(
                blank=True,
                default="Laboratorio de Anatomía Patológica\nFacultad de Ciencias Veterinarias",
                help_text="Texto libre que aparece en el PDF del informe debajo del nombre y la matrícula, junto a la imagen de la firma. Una línea por renglón. Ejemplo: Laboratorio de Anatomía Patológica / Facultad de Ciencias Veterinarias.",
                verbose_name="texto bajo la firma",
            ),
        ),
        migrations.AddField(
            model_name="laboratorystaff",
            name="signature_affiliation_text",
            field=models.TextField(
                blank=True,
                default="Laboratorio de Anatomía Patológica\nFacultad de Ciencias Veterinarias",
                help_text="Texto libre que aparece en el PDF del informe debajo del nombre y la matrícula, junto a la imagen de la firma. Una línea por renglón. Ejemplo:\nLaboratorio de Anatomía Patológica\nFacultad de Ciencias Veterinarias",
                verbose_name="texto bajo la firma",
            ),
        ),
    ]
